# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1105, 708)
        MainWindow.setStyleSheet("background: rgb(139, 139, 139)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background: rgb(139, 139, 139)")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, 0, 1131, 151))
        self.frame.setStyleSheet("background: rgb(37, 0, 186)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(170, 0, 591, 61))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(170, 50, 631, 61))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(28)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: yellow;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(170, 90, 721, 61))
        font = QtGui.QFont()
        font.setFamily("RomanD")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(30, 10, 121, 121))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("LOGO UNESA.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_3.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(-10, 140, 1121, 391))
        self.frame_2.setStyleSheet("background: rgb(139, 139, 139)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.listWidget = QtWidgets.QListWidget(self.frame_2)
        self.listWidget.setGeometry(QtCore.QRect(30, 80, 1061, 261))
        self.listWidget.setStyleSheet("background: white")
        self.listWidget.setObjectName("listWidget")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(40, 10, 481, 61))
        font = QtGui.QFont()
        font.setFamily("Swis721 Cn BT")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: white;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(40, 350, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Swis721 Lt BT")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: white;")
        self.label_6.setObjectName("label_6")
        self.label_Total = QtWidgets.QLabel(self.frame_2)
        self.label_Total.setGeometry(QtCore.QRect(160, 350, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Swis721 Lt BT")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_Total.setFont(font)
        self.label_Total.setStyleSheet("color: white;")
        self.label_Total.setObjectName("label_Total")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(-10, 540, 1121, 181))
        self.frame_3.setStyleSheet("background: white;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit.setGeometry(QtCore.QRect(40, 20, 1051, 41))
        self.lineEdit.setStyleSheet("background: rgb(139, 139, 139)")
        self.lineEdit.setObjectName("lineEdit")
        self.list_btn = QtWidgets.QPushButton(self.frame_3)
        self.list_btn.setGeometry(QtCore.QRect(50, 70, 331, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        self.list_btn.setFont(font)
        self.list_btn.setStyleSheet("background: rgb(139, 139, 139); color: white")
        self.list_btn.setObjectName("list_btn")
        self.delete_btn = QtWidgets.QPushButton(self.frame_3)
        self.delete_btn.setGeometry(QtCore.QRect(390, 70, 411, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        self.delete_btn.setFont(font)
        self.delete_btn.setStyleSheet("background: rgb(139, 139, 139); color: white")
        self.delete_btn.setObjectName("delete_btn")
        self.clear_btn = QtWidgets.QPushButton(self.frame_3)
        self.clear_btn.setGeometry(QtCore.QRect(810, 70, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        self.clear_btn.setFont(font)
        self.clear_btn.setStyleSheet("background: blue; color: white")
        self.clear_btn.setObjectName("clear_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.list_btn.clicked.connect(self.tambahTask)
        self.delete_btn.clicked.connect(self.hapusTask)
        self.clear_btn.clicked.connect(self.clearTask)
        

    def tambahTask(self):
        task = self.lineEdit.text()
        self.listWidget.addItem(task)
        self.lineEdit.setText("")
        if self.listWidget.count() == 0:
            self.label_Total.setText(str(0))
        else:
            self.label_Total.setText(str(self.hitungTotalTask(0)))
    
    def hitungTotalTask(self, index):
        if index == self.listWidget.count() - 1:
            return 1
        else:
            return 1 + self.hitungTotalTask(index + 1)

    def hapusTask(self):
        totalTaskSekarang = self.listWidget.count() - 1
        self.label_Total.setText(str(totalTaskSekarang))
        click = self.listWidget.currentRow()
        self.listWidget.takeItem(click)

    def clearTask(self):
        self.listWidget.clear()
        self.label_Total.setText(str("None"))
        
    def kurangiTask(self):
        totalTask = 0
        for i in range(self.listWidget.count()):
            tambahTask += 1
        self.label_Total.setText(str(tambahTask))


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TASKS SCHOOL MANAGEMENT"))
        self.label_2.setText(_translate("MainWindow", "UNIVERSITAS NEGERI SURABAYA"))
        self.label_3.setText(_translate("MainWindow", "Oleh Maulana Ardhiansyah Prasetyo Prodi S1 - Teknik Indormatika"))
        self.label_5.setText(_translate("MainWindow", "Task View"))
        self.label_6.setText(_translate("MainWindow", "Task Total :"))
        self.label_Total.setText(_translate("MainWindow", "None"))
        self.list_btn.setText(_translate("MainWindow", "Add Task"))
        self.delete_btn.setText(_translate("MainWindow", "Delete Task"))
        self.clear_btn.setText(_translate("MainWindow", "Clear Task"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
